PN2D - Add test ancnmnt for updating servers

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -24,9 +24,9 @@ jobs:
         -d '{"username": "GitHub Publish Changes", "avatar_url": "https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/refs/heads/master/logo.png", "content": "<a:nian:1179921939301670992> Запущено обновление по `${{GITHUB.REF_NAME}}` ветке!"}' \
         $DISCORD_PUBLISH_NOTIFY
   # SS220 Discord Notifier end
-    - name: Fail if we are attempting to run on the master branch
-      if: ${{GITHUB.REF_NAME == 'master' && github.repository == 'SerbiaStrong-220/space-station-14'}}
-      run: exit 1
+    # - name: Fail if we are attempting to run on the master branch
+    #   if: ${{GITHUB.REF_NAME == 'master' && github.repository == 'SerbiaStrong-220/space-station-14'}}
+    #   run: exit 1
 
   # SS220 custom install start
    # - name: Install dependencies
@@ -81,6 +81,7 @@ jobs:
         PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
         GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}
   # SS220 Discord Notifier bgn
+  # Обновление получено, сервер автоматически перезапустится для обновления в конце этого раунда.
     - name: SS220 PN2D - End
       if: success()
       env:
@@ -96,6 +97,22 @@ jobs:
       run: |
         curl -X POST -H "Content-Type: application/json" \
         -d '{"username": "GitHub Publish Changes", "avatar_url": "https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/refs/heads/master/logo.png", "content": "❌ Неуспешно обновление по `${{GITHUB.REF_NAME}}` ветке!"}' \
+        $DISCORD_PUBLISH_NOTIFY
+    - name: SS220 PN2D - Success Release Update
+      if: ${{GITHUB.REF_NAME == 'master' && github.repository == 'SerbiaStrong-220/space-station-14' && success()}}
+      env:
+        DISCORD_PUBLISH_NOTIFY: ${{ secrets.DISCORD_PUBLISH_NOTIFY }}
+      run: |
+        curl -X POST -H "Content-Type: application/json" \
+        -d '{
+          "username": "GitHub Publish Changes",
+          "avatar_url": "https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/refs/heads/master/logo.png",
+          "embeds": [{
+            "title": "Обновление отправлено на сервера <a:astronaut~1:1175836032667766814>",
+            "description": "Сервера автоматически перезапустятся для обновления в конце текущих раундов!",
+            "color": 3447003
+          }]
+        }' \
         $DISCORD_PUBLISH_NOTIFY
 # SS220 Discord Notifier end
 
